# =====================================================
# APPLICATION
# =====================================================

spring.application.name=cybercrime


# =====================================================
# SERVER
# =====================================================

server.port=8080


# =====================================================
# MYSQL DATABASE
# =====================================================

spring.datasource.url=jdbc:mysql://localhost:3306/cybercrime_db?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true

spring.datasource.username=root

spring.datasource.password=Cyber@123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =====================================================
# JPA / HIBERNATE
# =====================================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# =====================================================
# EMAIL / GMAIL SMTP
# =====================================================

spring.mail.host=smtp.gmail.com

spring.mail.port=587

spring.mail.username=cybercrimelocker2332@gmail.com

spring.mail.password=sblohbuyuqlaprwb

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.starttls.required=true


# =====================================================
# OTP SECURITY
# =====================================================

# OTP valid for 30 seconds
cybercrime.otp.expiry-seconds=30


# =====================================================
# SECURE ACCESS TOKEN
# =====================================================

# Secure token valid for 24 hours
cybercrime.secure-token.expiry-hours=24


# =====================================================
# AES-256-GCM ENCRYPTION
# =====================================================

cybercrime.encryption.key-base64=KIVo4in9qGUsBleRibCZyFRNNGVJpbiGNL8SSqMjo1A=


# =====================================================
# FILE STORAGE
# =====================================================

cybercrime.evidence.storage-path=evidence-storage